verify that UpcomingAlbums is mutated on github

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -56,3 +56,6 @@ jobs:
         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
         METALLUM_BOT_TOKEN: ${{ secrets.METALLUM_BOT_TOKEN }}
       run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=errebenito_metallumbot package --file pom.xml
+    - name: Show mutations file
+      run: grep -A 5 'UpcomingAlbums' target/pit-reports/mutations.xml || echo "Not found"
+  
